version: '3'

services:

  rabbitmq:
    image: rabbitmq:3.8-management
    container_name: broker_rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=broker_user
      - RABBITMQ_DEFAULT_PASS=broker_pass
    ports:
      - 5672:5672
      - 15672:15672

  redis:
    image: "redis"
    container_name: cache_redis
    restart: always
    ports:
      - 6379:6379
